package com.lumiring.minimacs.domain.constant;

public enum Code {
    JSON_NOT_READABLE,
    REQUEST_VALIDATION_ERROR,
    NOT_FOUND,
    BAD_CREDENTIALS,
    JWT_EXPIRED,
    USERNAME_BUSY,
    EMAIL_BUSY,
    INTERNAL_SERVER_ERROR,
    USER_NOT_FOUND,
    AUTHORIZATION_ERROR,
    MISSING_REQUEST_HEADER,
    METHOD_NOT_ALLOWED,
    NOT_READABLE,
    SUBSCRIPTION_LOGIC_ERROR,
    PUBLISHER_NOT_FOUND,
    ALREADY_SUBSCRIBED,
    ALREADY_EXISTS,
    NOT_SUPPORTED,
    NOT_BLOCK_YOURSELF,
    BLOCKED,
    TEST
}
